/**
 * Notification Dispatcher
 * Multi-channel alerts: Email + SMS + WhatsApp
 */

import { EmailService } from './emailService';
import { SMSService, SMSResult } from './smsService';
import { Alert } from '@/types';

export interface DispatchRequest {
    alert: Alert;
    email?: string;
    phone?: string;
    channels?: {
        email?: boolean;
        sms?: boolean;
        whatsapp?: boolean;
    };
}

export interface DispatchResult {
    email?: { success: boolean; details: string; simulated?: boolean };
    sms?: SMSResult;
    whatsappUrl?: string;
}

export class NotificationDispatcher {
    private static emailService = new EmailService();

    static async dispatch(req: DispatchRequest): Promise<DispatchResult> {
        const { alert, email, phone, channels } = req;
        const result: DispatchResult = {};

        // 1. Dispatch Email
        if (channels?.email && email) {
            try {
                const isConfigured = !!(process.env.SMTP_HOST && process.env.SMTP_USER);
                if (isConfigured) {
                    const sent = await this.emailService.sendAlertEmail(email, alert);
                    result.email = {
                        success: sent,
                        details: sent ? `Alert email delivered to ${email}` : `Failed to send email to ${email}`,
                    };
                } else {
                    console.log(`📧 [Email Dispatch Simulation] Alert: "${alert.title}" to ${email}`);
                    result.email = {
                        success: true,
                        simulated: true,
                        details: `Email notification prepared for ${email}. (Add SMTP_HOST, SMTP_USER, SMTP_PASS in .env.local for live SMTP delivery)`,
                    };
                }
            } catch (err: any) {
                result.email = {
                    success: false,
                    details: `Email error: ${err.message}`,
                };
            }
        }

        // 2. Dispatch SMS
        if (channels?.sms && phone) {
            const smsText = `🚨 GreenGuard AI Alert: ${alert.title}. ${alert.message} Recommended Action: Check irrigation dashboard.`;
            result.sms = await SMSService.sendAlertSMS(phone, smsText);
        }

        // 3. Prepare WhatsApp direct link
        if (channels?.whatsapp && phone) {
            const waText = `🌿 *GreenGuard AI Farm Alert*\n\n*${alert.title}*\n${alert.message}\n\n*Severity:* ${alert.severity.toUpperCase()}\n*Action Required:* ${alert.actionRequired ? 'YES' : 'Monitor'}\n\n_Generated by GreenGuard Smart Irrigation_`;
            result.whatsappUrl = SMSService.getWhatsAppUrl(phone, waText);
        }

        return result;
    }
}
